{% set version = "1.4.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-interpretmsspectrum
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/InterpretMSSpectrum_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/InterpretMSSpectrum/InterpretMSSpectrum_{{ version }}.tar.gz
  sha256: 8095ccb33db4b842a1b2dff7ed21237eea504e07a7828d6e84ab2edf0ec2ef53

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-envipat
    - r-plyr
  run:
    - r-base
    - r-envipat
    - r-plyr

test:
  commands:
    - $R -e "library('InterpretMSSpectrum')"           # [not win]
    - "\"%R%\" -e \"library('InterpretMSSpectrum')\""  # [win]

about:
  home: <doi:10.1021/acs.analchem.6b02743>
  license: GPL-3.0-only
  summary: High resolution mass spectrometry yields often large data sets of spectra from compounds which are not present in available libraries. These spectra need to be annotated and interpreted.'InterpretMSSpectrum' provides a set of functions to perform such tasks for Electrospray-Ionization and Atmospheric-Pressure-Chemical-Ionization
    derived data in positive and negative ionization mode.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
